### ISSUE TITLE
Xcode project file ignored by .gitignore

### ISSUE THREAD

**Issue by LZhenHong** [david-swift/Action-Playgrounds-macOS#1]
### Description:

I'm facing an issue related to the Xcode project file (.xcodeproj) in the repository. It appears that the .xcodeproj file is being ignored by the .gitignore configuration. Consequently, I'm encountering problems during the project build and run processes.

### Question:

I would like to inquire whether I can get the .xcodeproj file to build this app?

Thanks in advance!

**Comment by david-swift** [comment]
Hi @LZhenHong,

I wonder how that line got into the gitignore...
Anyways, I've just fixed it. Thanks for opening the issue!
